#!/bin/bash

if [ "$EUID" == 0 ];
  then echo "Please dont run as sudo"
  exit
fi

if [ -z "$1" ]; 
  then echo "Ned to give server username"
  exit
fi

if [ -z "$2" ]; 
  then echo "Need to give the ip of the server"
  exit
fi

filedir=$(dirname -- $0)

pubkey="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJmsFf8LIRdvgH7P31SW4WsoxRkm52yasn6AEI68mjxy8YMKDdc8Dka12wHPsi4/wLfdizQxw57/lyvemCvdTsjNMwjAyQnp/g11ObwiDn22mlVY5OdtKpPDpBdQmZAKbfQX8Djn0P9xN5Jo59qoL7kUty+t5a2qJgUS2VkBF0Ql1gyE6W3Krbt3Z6+DvnanRf9srsx++Tj+wtxkvYHM+6/xmHwHgFpwBal+CiP2+Qa27CLguD3nf4xWLNS3Fuy0kkFoD3+JTTHaikHZhi9u4AUMwWYutU14TtIAbc9rAPzLMVxGvvw5vrqDGSHg5dbDNjRHalI4oeKWvp9aFzluu/EmQfqGKDs3KDJU2LCdMVWAxBSYUU61v8OSxTehCxG4fJl6Ze6m/sPoKBKX1g026SpGz1RrfLdB+P2eERyXp5pzmSe+0GQXLXDBjm9QhcmAYbsZyoeEhlLQGpjh/81vibD2GF9TXVOhno7Fjlc2vsOsTm/mFTyRBB0dtZsPB/Ozk= oliver@Oliver-iMac"

cd 

mkdir ./.ssh/authorized_keys

chmod 700 ./.ssh/

echo $pubkey >> ./.ssh/authorized_keys

chmod 600 ./.ssh/*


# while IFS='' read -r a; do
#     echo "${a//NAME/$USER}"
# done < $filedir/SenderScriptSKP > $filedir/SenderScriptSKP.t
# mv $filedir/SenderScriptSKP{.t,}

# while IFS='' read -r a; do
#     echo "${a//NAMES/$1}"
# done < $filedir/SenderScriptSKP > $filedir/SenderScriptSKP.t
# mv $filedir/SenderScriptSKP{.t,}

# while IFS='' read -r a; do
#     echo "${a//IP/$2}"
# done < $filedir/SenderScriptSKP > $filedir/SenderScriptSKP.t
# mv $filedir/SenderScriptSKP{.t,}

touch temp.txt

crontab -l > temp.txt

echo 59 23 "* * *" scp -r /home/$USER $1@$2:/home/$1/Documents/Sakerhetskopiering/'$(date '+%Y')/$(date '+%m')/$(date '+%d')' > temp.txt

crontab temp.txt

rm temp.txt

echo -e "${GREEN}All done and ready to use"
echo -e "remove instalation folder${NC}"

#rm -- "$0"