#!/bin/bash

if [ "$EUID" == 0 ];
  then echo "Please dont run as sudo"
  exit
fi

if [ -z "$1" ]; 
  then echo "Ned to give server username"
  exit
fi

if [ -z "$2" ]; 
  then echo "Need to give the ip of the server"
  exit
fi

filedir=$(dirname -- $0)

pubkey="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTBHNVFVq+fkUvuaNd1obNNdGzoe72hNBRAppCGIn9vZgms9EhWbn61aGRv3B6evi40TgKMgqjPvPu6XyHNEbThbtPnFyLlkXyeY9Z/tBtPjFKbLGGXsNoXE7R60ZZbFz/PkWSD3BN3fmMPcUJ5ep1XzNh5J+4pXkQlwPD6qfkbR/EgjNO40NJqZDXiPRDCrfE5PbZPrXMGmiFLB6Tl+3ZoCcJmsnVbNnE3yGRrNm0EXnWAHQ9FSlOXf2h4c6F3I6YNuoD3M2kScA5q98+8rieAadGBxiusHgEGJH8UiMGAveHVCmOIv5mGxpzPp3bG4ne1CHbSBQm+OwrmdwLnM+f+GDDesLyV3LYzJdo1R3iT75xLsVuD62iDm0J3Rhz+WDYWarZRzjFSm3shbhIzl8A/uu11LPDmh53qa0oclWRsXZt94vFI0cWlWtppf4zps+OgggleyKNEdYxk6QDO7mMZ5SS9WJcuvAILCLyJWbbOhvmNPTVgG8nDAQLi+ZBrTE= oliver@oliver-ThinkCentre-M720s"

cd 

touch ./.ssh/authorized_keys

chmod 700 ./.ssh/

echo $pubkey > ./.ssh/authorized_keys

chmod 600 ./.ssh/*


# while IFS='' read -r a; do
#     echo "${a//NAME/$USER}"
# done < $filedir/SenderScriptSKP > $filedir/SenderScriptSKP.t
# mv $filedir/SenderScriptSKP{.t,}

# while IFS='' read -r a; do
#     echo "${a//NAMES/$1}"
# done < $filedir/SenderScriptSKP > $filedir/SenderScriptSKP.t
# mv $filedir/SenderScriptSKP{.t,}

# while IFS='' read -r a; do
#     echo "${a//IP/$2}"
# done < $filedir/SenderScriptSKP > $filedir/SenderScriptSKP.t
# mv $filedir/SenderScriptSKP{.t,}

touch temp.txt

crontab -l > temp.txt

command='ssh $1@$2 "mkdir -p /home/$1/Documents/Sakerhetskopiering/$(date +%Y)/$(date +%m)/$(date +%d)" && scp -pr /home/$USER/Desktop/Music $1@$2:/home/$1/Documents/Sakerhetskopiering/$(date +%Y)/$(date +%m)/$(date +%d)'

echo 59 23 '* * *' ssh $1@$2 '"mkdir -p /home/$1/Documents/Sakerhetskopiering/$(date +"\%Y")/$(date +"\%m")/$(date +"\%d")"' '&& scp -r /home/'$USER/'*' $1@$2:/home/$1/Documents/Sakerhetskopiering/'$(date +"\%Y")/$(date +"\%m")/$(date +"\%d")'

crontab temp.txt

rm temp.txt

echo -e "${GREEN}All done and ready to use"
echo -e "remove instalation folder${NC}"

#rm -- "$0"